"""The shipped per-terrain country borders.

Geometry is generated by ``scripts/build_country_borders.py``; these pin the
properties a regeneration must not quietly lose.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from game.theater.terrainborders import load_terrain_borders

SHIPPED = [
    "Afghanistan",
    "Syria",
    "Caucasus",
    "Iraq",
    "Kola",
    "PersianGulf",
    "Sinai",
    "Falklands",
]


@pytest.mark.parametrize("terrain", SHIPPED)
def test_every_shipped_terrain_parses(terrain: str) -> None:
    entries = load_terrain_borders(terrain)
    assert entries, f"{terrain} ships no borders"
    for entry in entries:
        assert entry["country"]
        assert len(entry["border"]) >= 3


def test_terrain_name_matching_is_forgiving() -> None:
    """The pydcs terrain name is what callers have; the filename is lowercase."""
    assert load_terrain_borders("Afghanistan") == load_terrain_borders("afghanistan")


def test_a_terrain_with_no_file_is_empty_not_an_error() -> None:
    """Nevada and the Marianas have no foreign border to draw."""
    assert load_terrain_borders("Nevada") == []


def test_an_unreadable_directory_costs_the_borders_not_the_mission() -> None:
    assert load_terrain_borders("Afghanistan", Path("does/not/exist")) == []


def test_the_map_draws_its_own_nation() -> None:
    """The country the map is named after is a country like any other.

    Leaving the host out deletes Russia from Kola and Iran from the Persian
    Gulf -- the most relevant border on each of those maps -- and leaves the
    middle of the map as the one region with no line on it.
    """
    hosts = {
        "Afghanistan": "Afghanistan",
        "Syria": "Syria",
        "Iraq": "Iraq",
        "Sinai": "Egypt",
        "Kola": "Russia",
        "PersianGulf": "Iran",
        "Caucasus": "Georgia",
    }
    for terrain, host in hosts.items():
        names = {e["country"] for e in load_terrain_borders(terrain)}
        assert host in names, f"{terrain} does not draw its own nation"


@pytest.mark.parametrize("terrain", SHIPPED)
def test_no_zone_is_a_clip_artifact(terrain: str) -> None:
    """A clip box wider than the map leaves triangles hanging off its edge.

    Sinai first shipped a 3-vertex Saudi sliver of 1,629 km2 at lng 37.0-37.5,
    past the map's own 36.61 -- real territory cut into a meaningless wedge by
    the box rather than by a coastline. Bounding by airfield extent cannot catch
    it (the Afghanistan map reaches empty sea at 24.5N for the carrier), so the
    test is on the shape: a border simplified from a real country keeps its
    corners, an artifact collapses to a few.
    """
    for entry in load_terrain_borders(terrain):
        border = entry["border"]
        area_km2 = (
            abs(
                sum(
                    border[i][0] * border[(i + 1) % len(border)][1]
                    - border[(i + 1) % len(border)][0] * border[i][1]
                    for i in range(len(border))
                )
            )
            / 2
            / 1e6
        )
        # Bahrain really is a 571 km2 island and a quad is the honest shape for
        # it. It is the only sub-1000 km2 country on any shipped map.
        if entry["country"] == "Bahrain":
            continue
        assert not (len(border) < 6 and area_km2 < 5000), (
            f"{terrain}/{entry['country']}: {len(border)} vertices over "
            f"{area_km2:.0f} km2 reads as a clip artifact, not a border"
        )


def test_an_archipelago_does_not_become_a_dozen_zones() -> None:
    """Tierra del Fuego needs an area floor: unfiltered, Chile alone came out
    as five zones, one of them the 1,439 km2 Cape Horn group."""
    zones = load_terrain_borders("Falklands")
    assert len(zones) <= 8, "the Falklands archipelago was not floored"
    by_country: dict[str, int] = {}
    for entry in zones:
        by_country[entry["country"]] = by_country.get(entry["country"], 0) + 1
    for country, count in by_country.items():
        assert count <= 4, f"{country} fragmented into {count} zones"


def test_a_complex_coast_is_not_simplified_into_a_blob() -> None:
    """Norway is the worst shape the simplifier meets here: a thin fjord coast
    wrapping around Sweden. Measured by symmetric difference against the true
    clipped country: 30.2% wrong at a 24-vertex budget, 7.31% at 96, and 1.28%
    at the 384 shipped now. This pins that a regeneration did not quietly drop
    the budget -- 96 put Norway at 93 vertices."""
    norway = [e for e in load_terrain_borders("Kola") if e["country"] == "Norway"]
    assert norway, "Kola no longer draws Norway"
    assert len(norway[0]["border"]) >= 250, (
        f"Norway came out at {len(norway[0]['border'])} vertices -- at that "
        "budget its coastline is a blob"
    )


@pytest.mark.parametrize("terrain", SHIPPED)
def test_neighbours_do_not_overlap(terrain: str) -> None:
    """Two countries cannot both hold the same ground.

    Each country used to be simplified on its own, so a shared frontier came out
    as two lines that weave: neighbours' lines coincided only 35-65% of the time
    and left slivers of overlap up to 12.8% of the smaller country. The whole
    map is simplified as one coverage now.
    """
    from shapely.geometry import Polygon

    polys = [
        (entry["country"], Polygon(entry["border"]).buffer(0))
        for entry in load_terrain_borders(terrain)
    ]
    for index, (name_a, poly_a) in enumerate(polys):
        for name_b, poly_b in polys[index + 1 :]:
            overlap = poly_a.intersection(poly_b).area
            assert (
                overlap < 1000.0
            ), f"{terrain}: {name_a} and {name_b} overlap by {overlap / 1e6:.1f} km2"


@pytest.mark.parametrize("terrain", SHIPPED)
def test_a_shared_frontier_is_one_line(terrain: str) -> None:
    """Each map is a valid polygon coverage: non-overlapping AND edge-matched,
    so a border two countries share is the same vertices on both sides rather
    than two independent traces of it.

    Falklands is the one exception and is asserted as such: Argentina and Chile
    interlock across Tierra del Fuego, and writing the rings as whole metres
    leaves a 12.5 m2 degenerate touch there -- far below anything drawable.
    """
    import shapely
    from shapely.geometry import Polygon

    if terrain == "Falklands":
        pytest.skip("known 12.5 m2 degenerate touch in Tierra del Fuego")
    polys = [Polygon(e["border"]).buffer(0) for e in load_terrain_borders(terrain)]
    assert bool(
        shapely.coverage_is_valid(polys)
    ), f"{terrain} is not a valid coverage: a shared frontier is drawn twice"


def test_the_label_lands_inside_the_country_it_names() -> None:
    """A national border is usually concave -- Norway spectacularly so -- and a
    centroid lands in the sea or inside the neighbour."""
    from shapely.geometry import Point, Polygon

    from game.missiongenerator.borderluadata import label_point

    for terrain in SHIPPED:
        for entry in load_terrain_borders(terrain):
            point = label_point(entry["border"])
            assert point is not None, f"{terrain}/{entry['country']} has no label point"
            polygon = Polygon(entry["border"]).buffer(0)
            assert polygon.contains(
                Point(point)
            ), f"{terrain}/{entry['country']}'s name would be written outside it"


def test_a_higher_budget_did_not_reintroduce_slivers() -> None:
    """Finer geometry stops absorbing slivers, so the budget needs an area floor.

    At 384 with no floor, Kola gained a 340 km2 / 6-vertex Russian fragment and
    a 0 km2 / 3-vertex Norwegian one -- each of which would be drawn and labelled
    as a country. 500 km2 cuts between those and the smallest genuine
    territories: Bahrain 598 km2, Oman's Musandam 1,799, Iran's coastal piece
    1,973, all with 32+ vertices.
    """
    from shapely.geometry import Polygon

    for terrain in SHIPPED:
        for entry in load_terrain_borders(terrain):
            area_km2 = Polygon(entry["border"]).area / 1e6
            assert area_km2 >= 400, (
                f"{terrain}/{entry['country']} is a {area_km2:.0f} km2 sliver -- "
                "regenerate with --min-area-km2"
            )
