"""Real national borders for a terrain, drawn on the F10 map.

Borders are a property of the *map*, not of a campaign: they are identical for
every campaign on a given terrain, so they ship once per terrain in
``resources/borders/<terrain>.yaml`` and every campaign on that map gets them
for free. A campaign author does nothing.

Each entry carries a country name and a ring of terrain XY vertices, and
nothing else. The geometry is generated by ``tools/build_country_borders.py``
from real boundary data -- edit the tool, not the yaml.

A terrain with no file simply has no borders to draw, which is the correct
answer for Nevada and the Marianas: every airfield on them belongs to one
country, so a border would be a line around the whole map.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

BORDERS_DIR = Path("resources/borders")


def load_terrain_borders(
    terrain_name: str, directory: Path | None = None
) -> list[dict[str, Any]]:
    """Border entries for a terrain, or an empty list.

    Never raises. A malformed or missing file costs the borders on the F10 map
    and nothing else, so it must not be able to take a mission down with it.
    """
    folder = BORDERS_DIR if directory is None else directory
    path = folder / f"{terrain_name.lower()}.yaml"
    if not path.is_file():
        return []
    try:
        with path.open("r", encoding="utf-8") as handle:
            data = yaml.safe_load(handle) or {}
    except Exception:
        logging.warning("Could not read borders from %s.", path, exc_info=True)
        return []
    zones = data.get("zones")
    if not isinstance(zones, list):
        return []
    entries = []
    for zone in zones:
        if not isinstance(zone, dict):
            continue
        country = zone.get("country")
        border = zone.get("border")
        if not country or not isinstance(border, list) or len(border) < 3:
            continue
        try:
            ring = [(float(x), float(y)) for x, y in border]
        except (TypeError, ValueError):
            logging.warning("Skipping a malformed border for %s.", country)
            continue
        entries.append({"country": str(country), "border": ring})
    return entries
